/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2017
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 07:17:27 PM IST 
//


package com.ericsson.nms.security.nscs.handler.ciphersconfig.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeCiphers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeCiphers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="nodes" type="{}Nodes"/>
 *         &lt;element name="sshProtocol" type="{}sshProtocol" minOccurs="0"/>
 *         &lt;element name="tlsProtocol" type="{}tlsProtocol" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeCiphers", propOrder = {

})
public class NodeCiphers {

    @XmlElement(required = true)
    protected Nodes nodes;
    protected SshProtocol sshProtocol;
    protected TlsProtocol tlsProtocol;

    /**
     * Gets the value of the nodes property.
     * 
     * @return
     *     possible object is
     *     {@link Nodes }
     *     
     */
    public Nodes getNodes() {
        return nodes;
    }

    /**
     * Sets the value of the nodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nodes }
     *     
     */
    public void setNodes(Nodes value) {
        this.nodes = value;
    }

    /**
     * Gets the value of the sshProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link SshProtocol }
     *     
     */
    public SshProtocol getSshProtocol() {
        return sshProtocol;
    }

    /**
     * Sets the value of the sshProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link SshProtocol }
     *     
     */
    public void setSshProtocol(SshProtocol value) {
        this.sshProtocol = value;
    }

    /**
     * Gets the value of the tlsProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link TlsProtocol }
     *     
     */
    public TlsProtocol getTlsProtocol() {
        return tlsProtocol;
    }

    /**
     * Sets the value of the tlsProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link TlsProtocol }
     *     
     */
    public void setTlsProtocol(TlsProtocol value) {
        this.tlsProtocol = value;
    }

}
