/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2017
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 07:17:27 PM IST 
//


package com.ericsson.nms.security.nscs.handler.ciphersconfig.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sshProtocol complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sshProtocol">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="keyExchangeCiphers" type="{}keyExchangeCiphers" minOccurs="0"/>
 *         &lt;element name="encryptCiphers" type="{}encryptCiphers" minOccurs="0"/>
 *         &lt;element name="macCiphers" type="{}macCiphers" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sshProtocol", propOrder = {

})
public class SshProtocol {

    protected KeyExchangeCiphers keyExchangeCiphers;
    protected EncryptCiphers encryptCiphers;
    protected MacCiphers macCiphers;

    /**
     * Gets the value of the keyExchangeCiphers property.
     * 
     * @return
     *     possible object is
     *     {@link KeyExchangeCiphers }
     *     
     */
    public KeyExchangeCiphers getKeyExchangeCiphers() {
        return keyExchangeCiphers;
    }

    /**
     * Sets the value of the keyExchangeCiphers property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyExchangeCiphers }
     *     
     */
    public void setKeyExchangeCiphers(KeyExchangeCiphers value) {
        this.keyExchangeCiphers = value;
    }

    /**
     * Gets the value of the encryptCiphers property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptCiphers }
     *     
     */
    public EncryptCiphers getEncryptCiphers() {
        return encryptCiphers;
    }

    /**
     * Sets the value of the encryptCiphers property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptCiphers }
     *     
     */
    public void setEncryptCiphers(EncryptCiphers value) {
        this.encryptCiphers = value;
    }

    /**
     * Gets the value of the macCiphers property.
     * 
     * @return
     *     possible object is
     *     {@link MacCiphers }
     *     
     */
    public MacCiphers getMacCiphers() {
        return macCiphers;
    }

    /**
     * Sets the value of the macCiphers property.
     * 
     * @param value
     *     allowed object is
     *     {@link MacCiphers }
     *     
     */
    public void setMacCiphers(MacCiphers value) {
        this.macCiphers = value;
    }

}
