//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}metaData"/>
 *         &lt;element ref="{}security" minOccurs="0"/>
 *         &lt;element ref="{}ipsec" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metaData",
    "security",
    "ipsec"
})
@XmlRootElement(name = "body")
public class Body {

    @XmlElement(required = true)
    protected MetaData metaData;
    protected Security security;
    protected List<Ipsec> ipsec;


    /**
     * Gets the value of the metaData property.
     *
     * @return possible object is {@link MetaData }
     *
     */
    public MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     *
     * @param value allowed object is {@link MetaData }
     *
     */
    public void setMetaData(final MetaData value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the security property.
     *
     * @return possible object is {@link Security }
     *
     */
    public Security getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     *
     * @param value allowed object is {@link Security }
     *
     */
    public void setSecurity(final Security value) {
        this.security = value;
    }

    /**
     * Gets the value of the ipsec property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the ipsec property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpsec().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Ipsec }
     *
     *
     */
    public List<Ipsec> getIpsec() {
        if (ipsec == null) {
            ipsec = new ArrayList<Ipsec>();
        }
        return this.ipsec;
    }

}
