//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}EncryptedContent">
 *       &lt;attribute name="category" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="certFingerprint" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="certSerialNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "certFile")
public class CertFile
        extends ISCFEncryptedContent {

    @XmlAttribute(name = "category", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String category;
    @XmlAttribute(name = "certFingerprint", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String certFingerprint;
    @XmlAttribute(name = "certSerialNumber", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String certSerialNumber;

    /**
     * Gets the value of the category property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCategory(final String value) {
        this.category = value;
    }

    /**
     * Gets the value of the certFingerprint property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCertFingerprint() {
        return certFingerprint;
    }

    /**
     * Sets the value of the certFingerprint property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCertFingerprint(final String value) {
        this.certFingerprint = value;
    }

    /**
     * Gets the value of the certSerialNumber property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCertSerialNumber() {
        return certSerialNumber;
    }

    /**
     * Sets the value of the certSerialNumber property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCertSerialNumber(final String value) {
        this.certSerialNumber = value;
    }

}
