//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
 *       &lt;attribute name="PBKDF2salt" use="required" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="PBKDF2iterationCount" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;minInclusive value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "encryptedContent")
public class EncryptedContent {

    @XmlValue
    protected byte[] value;
    @XmlAttribute(name = "PBKDF2salt", required = true)
    protected byte[] pbkdf2Salt;
    @XmlAttribute(name = "PBKDF2iterationCount", required = true)
    protected BigInteger pbkdf2IterationCount;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is byte[]
     */
    public byte[] getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is byte[]
     */
    public void setValue(final byte[] value) {
        this.value = value;
    }

    /**
     * Gets the value of the pbkdf2Salt property.
     *
     * @return possible object is byte[]
     */
    public byte[] getPBKDF2Salt() {
        return pbkdf2Salt;
    }

    /**
     * Sets the value of the pbkdf2Salt property.
     *
     * @param value allowed object is byte[]
     */
    public void setPBKDF2Salt(final byte[] value) {
        this.pbkdf2Salt = value;
    }

    /**
     * Gets the value of the pbkdf2IterationCount property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getPBKDF2IterationCount() {
        return pbkdf2IterationCount;
    }

    /**
     * Sets the value of the pbkdf2IterationCount property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setPBKDF2IterationCount(final BigInteger value) {
        this.pbkdf2IterationCount = value;
    }

}
