//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import com.ericsson.nms.security.nscs.api.iscf.BaseSubjectAltNameDataType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}EnrollmentData">
 *       &lt;attribute name="subjectAltNameType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="subjectAltName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ipsecEnrollmentData")
public class IpsecEnrollmentData
        extends ISCFEnrollmentData {

    @XmlAttribute(name = "subjectAltNameType")
    protected Integer subjectAltNameType;
    
    @XmlAttribute(name = "subjectAltName")
    @XmlSchemaType(name = "anySimpleType")
    protected String subjectAltName;

    @XmlAttribute(name = "rollbackTimeout", required = true)
    protected int rollbackTimeout;

    /**
     * Gets the value of the subjectAltNameType property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public int getSubjectAltNameType() {
        return subjectAltNameType;
    }

    /**
     * Sets the value of the subjectAltNameType property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setSubjectAltNameType(final int value) {
        this.subjectAltNameType = value;
    }

    /**
     * Gets the value of the subjectAltName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSubjectAltName() {
        return subjectAltName;
    }

    /**
     * Sets the value of the subjectAltName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSubjectAltName(final String value) {
        this.subjectAltName = value;
    }

    /**
     * Gets the value of the rollbackTimeout property.
     *
     * @return 
     */
    public int getRollbackTimeout() {
        return rollbackTimeout;
    }

    /**
     * Sets the value of the rollbackTimeout property.
     *
     * @param value
     */
    public void setRollbackTimeout(final int value) {
        this.rollbackTimeout = value;
    }
}
