//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ipsecFiles"/>
 *         &lt;element ref="{}ipsecEnrollmentData"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="userLabel">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="128"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="certExpirWarnTime">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;minInclusive value="2"/>
 *             &lt;maxInclusive value="365"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ipsecFiles",
    "ipsecEnrollmentData"
})
@XmlRootElement(name = "ipsec")
public class Ipsec {

    @XmlElement(required = true)
    protected IpsecFiles ipsecFiles;
    @XmlElement(required = true)
    protected IpsecEnrollmentData ipsecEnrollmentData;
    @XmlAttribute(name = "type")
    @XmlSchemaType(name = "anySimpleType")
    protected String type;
    @XmlAttribute(name = "userLabel")
    protected String userLabel;
    @XmlAttribute(name = "certExpirWarnTime")
    protected Integer certExpirWarnTime;

    /**
     * Gets the value of the ipsecFiles property.
     *
     * @return possible object is {@link IpsecFiles }
     *
     */
    public IpsecFiles getIpsecFiles() {
        return ipsecFiles;
    }

    /**
     * Sets the value of the ipsecFiles property.
     *
     * @param value allowed object is {@link IpsecFiles }
     *
     */
    public void setIpsecFiles(final IpsecFiles value) {
        this.ipsecFiles = value;
    }

    /**
     * Gets the value of the ipsecEnrollmentData property.
     *
     * @return possible object is {@link IpsecEnrollmentData }
     *
     */
    public IpsecEnrollmentData getIpsecEnrollmentData() {
        return ipsecEnrollmentData;
    }

    /**
     * Sets the value of the ipsecEnrollmentData property.
     *
     * @param value allowed object is {@link IpsecEnrollmentData }
     *
     */
    public void setIpsecEnrollmentData(final IpsecEnrollmentData value) {
        this.ipsecEnrollmentData = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setType(final String value) {
        this.type = value;
    }

    /**
     * Gets the value of the userLabel property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUserLabel() {
        return userLabel;
    }

    /**
     * Sets the value of the userLabel property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUserLabel(final String value) {
        this.userLabel = value;
    }

    /**
     * Gets the value of the certExpirWarnTime property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getCertExpirWarnTime() {
        return certExpirWarnTime;
    }

    /**
     * Sets the value of the certExpirWarnTime property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setCertExpirWarnTime(final Integer value) {
        this.certExpirWarnTime = value;
    }

}
