//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Encrypted content for ISCF XML output.
 *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncryptedContent", propOrder = {
    "encryptedContent"
})
@XmlSeeAlso({
    CertFile.class
})
public class ISCFEncryptedContent {

    @XmlElement(required = true)
    protected EncryptedContent encryptedContent;

    /**
     * Gets the value of the encryptedContent property.
     *
     * @return possible object is {@link EncryptedContent }
     *
     */
    public EncryptedContent getEncryptedContent() {
        return encryptedContent;
    }

    /**
     * Sets the value of the encryptedContent property.
     *
     * @param value allowed object is {@link EncryptedContent }
     *
     */
    public void setEncryptedContent(final EncryptedContent value) {
        this.encryptedContent = value;
    }

}
