//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}level2ConfigSettings"/>
 *         &lt;element ref="{}level2Files"/>
 *         &lt;element ref="{}secEnrollmentData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "level2ConfigSettings",
    "level2Files",
    "secEnrollmentData"
})
@XmlRootElement(name = "level2")
public class Level2 {

    @XmlElement(required = true)
    protected Level2ConfigSettings level2ConfigSettings;
    @XmlElement(required = true)
    protected Level2Files level2Files;
    @XmlElement(required = true)
    protected SecEnrollmentData secEnrollmentData;

    /**
     * Gets the value of the level2ConfigSettings property.
     *
     * @return possible object is {@link Level2ConfigSettings }
     *
     */
    public Level2ConfigSettings getLevel2ConfigSettings() {
        return level2ConfigSettings;
    }

    /**
     * Sets the value of the level2ConfigSettings property.
     *
     * @param value allowed object is {@link Level2ConfigSettings }
     *
     */
    public void setLevel2ConfigSettings(final Level2ConfigSettings value) {
        this.level2ConfigSettings = value;
    }

    /**
     * Gets the value of the level2Files property.
     *
     * @return possible object is {@link Level2Files }
     *
     */
    public Level2Files getLevel2Files() {
        return level2Files;
    }

    /**
     * Sets the value of the level2Files property.
     *
     * @param value allowed object is {@link Level2Files }
     *
     */
    public void setLevel2Files(final Level2Files value) {
        this.level2Files = value;
    }

    /**
     * Gets the value of the secEnrollmentData property.
     *
     * @return possible object is {@link SecEnrollmentData }
     *
     */
    public SecEnrollmentData getSecEnrollmentData() {
        return secEnrollmentData;
    }

    /**
     * Sets the value of the secEnrollmentData property.
     *
     * @param value allowed object is {@link SecEnrollmentData }
     *
     */
    public void setSecEnrollmentData(final SecEnrollmentData value) {
        this.secEnrollmentData = value;
    }

}
