//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}logonServerAddress" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="certExpirWarnTime">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;minInclusive value="2"/>
 *             &lt;maxInclusive value="365"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="installTrustedCertDuration" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;minInclusive value="5"/>
 *             &lt;maxInclusive value="600"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "logonServerAddress"
})
@XmlRootElement(name = "level2ConfigSettings")
public class Level2ConfigSettings {

    @XmlElement(required = true)
    protected List<String> logonServerAddress;
    @XmlAttribute(name = "certExpirWarnTime")
    protected Integer certExpirWarnTime;
    @XmlAttribute(name = "installTrustedCertDuration", required = true)
    protected int installTrustedCertDuration;

    /**
     * Gets the value of the logonServerAddress property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the logonServerAddress property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogonServerAddress().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     *
     *
     * @return 
     */
    public List<String> getLogonServerAddress() {
        if (logonServerAddress == null) {
            logonServerAddress = new ArrayList<>();
        }
        return this.logonServerAddress;
    }

    /**
     * Gets the value of the certExpirWarnTime property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getCertExpirWarnTime() {
        return certExpirWarnTime;
    }

    /**
     * Sets the value of the certExpirWarnTime property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setCertExpirWarnTime(final Integer value) {
        this.certExpirWarnTime = value;
    }

    /**
     * Gets the value of the installTrustedCertDuration property.
     *
     */
    public int getInstallTrustedCertDuration() {
        return installTrustedCertDuration;
    }

    /**
     * Sets the value of the installTrustedCertDuration property.
     *
     */
    public void setInstallTrustedCertDuration(final int value) {
        this.installTrustedCertDuration = value;
    }

}
