//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}aaServerIPAddressList"/>
 *       &lt;/sequence>
 *       &lt;attribute name="securityLevel3Timeout">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;minInclusive value="5"/>
 *             &lt;maxInclusive value="300"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="authorizationCacheTimeOut">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;minInclusive value="15"/>
 *             &lt;maxInclusive value="480"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="installLaadDuration" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;minInclusive value="5"/>
 *             &lt;maxInclusive value="600"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aaServerIPAddressList"
})
@XmlRootElement(name = "level3ConfigSettings")
public class Level3ConfigSettings {

    @XmlElement(required = true)
    protected AaServerIPAddressList aaServerIPAddressList;
    @XmlAttribute(name = "securityLevel3Timeout")
    protected Integer securityLevel3Timeout;
    @XmlAttribute(name = "authorizationCacheTimeOut")
    protected Integer authorizationCacheTimeOut;
    @XmlAttribute(name = "installLaadDuration", required = true)
    protected int installLaadDuration;

    /**
     * Gets the value of the aaServerIPAddressList property.
     *
     * @return possible object is {@link AaServerIPAddressList }
     *
     */
    public AaServerIPAddressList getAaServerIPAddressList() {
        return aaServerIPAddressList;
    }

    /**
     * Sets the value of the aaServerIPAddressList property.
     *
     * @param value allowed object is {@link AaServerIPAddressList }
     *
     */
    public void setAaServerIPAddressList(final AaServerIPAddressList value) {
        this.aaServerIPAddressList = value;
    }

    /**
     * Gets the value of the securityLevel3Timeout property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getSecurityLevel3Timeout() {
        return securityLevel3Timeout;
    }

    /**
     * Sets the value of the securityLevel3Timeout property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setSecurityLevel3Timeout(final Integer value) {
        this.securityLevel3Timeout = value;
    }

    /**
     * Gets the value of the authorizationCacheTimeOut property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getAuthorizationCacheTimeOut() {
        return authorizationCacheTimeOut;
    }

    /**
     * Sets the value of the authorizationCacheTimeOut property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setAuthorizationCacheTimeOut(final Integer value) {
        this.authorizationCacheTimeOut = value;
    }

    /**
     * Gets the value of the installLaadDuration property.
     *
     */
    public int getInstallLaadDuration() {
        return installLaadDuration;
    }

    /**
     * Sets the value of the installLaadDuration property.
     *
     */
    public void setInstallLaadDuration(final int value) {
        this.installLaadDuration = value;
    }

}
