//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}certFile" maxOccurs="unbounded"/>
 *         &lt;element ref="{}localAuthenticationDB"/>
 *         &lt;element ref="{}localAuthorizationDB"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "certFile",
    "localAuthenticationDB",
    "localAuthorizationDB"
})
@XmlRootElement(name = "level3Files")
public class Level3Files {

    @XmlElement(required = true)
    protected List<CertFile> certFile;
    @XmlElement(required = true)
    protected ISCFEncryptedContent localAuthenticationDB;
    @XmlElement(required = true)
    protected ISCFEncryptedContent localAuthorizationDB;

    /**
     * Gets the value of the certFile property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the certFile property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCertFile().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CertFile }
     *
     *
     * @return 
     */
    public List<CertFile> getCertFile() {
        if (certFile == null) {
            certFile = new ArrayList<>();
        }
        return this.certFile;
    }

    /**
     * Gets the value of the localAuthenticationDB property.
     *
     * @return possible object is {@link ISCFEncryptedContent }
     *
     */
    public ISCFEncryptedContent getLocalAuthenticationDB() {
        return localAuthenticationDB;
    }

    /**
     * Sets the value of the localAuthenticationDB property.
     *
     * @param value allowed object is {@link ISCFEncryptedContent }
     *
     */
    public void setLocalAuthenticationDB(final ISCFEncryptedContent value) {
        this.localAuthenticationDB = value;
    }

    /**
     * Gets the value of the localAuthorizationDB property.
     *
     * @return possible object is {@link ISCFEncryptedContent }
     *
     */
    public ISCFEncryptedContent getLocalAuthorizationDB() {
        return localAuthorizationDB;
    }

    /**
     * Sets the value of the localAuthorizationDB property.
     *
     * @param value allowed object is {@link ISCFEncryptedContent }
     *
     */
    public void setLocalAuthorizationDB(final ISCFEncryptedContent value) {
        this.localAuthorizationDB = value;
    }

}
