//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}level3ConfigSettings"/>
 *         &lt;element ref="{}level3Files"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "level3ConfigSettings",
    "level3Files"
})
@XmlRootElement(name = "level3")
public class Level3 {

    @XmlElement(required = true)
    protected Level3ConfigSettings level3ConfigSettings;
    @XmlElement(required = true)
    protected Level3Files level3Files;

    /**
     * Gets the value of the level3ConfigSettings property.
     *
     * @return possible object is {@link Level3ConfigSettings }
     *
     */
    public Level3ConfigSettings getLevel3ConfigSettings() {
        return level3ConfigSettings;
    }

    /**
     * Sets the value of the level3ConfigSettings property.
     *
     * @param value allowed object is {@link Level3ConfigSettings }
     *
     */
    public void setLevel3ConfigSettings(final Level3ConfigSettings value) {
        this.level3ConfigSettings = value;
    }

    /**
     * Gets the value of the level3Files property.
     *
     * @return possible object is {@link Level3Files }
     *
     */
    public Level3Files getLevel3Files() {
        return level3Files;
    }

    /**
     * Sets the value of the level3Files property.
     *
     * @param value allowed object is {@link Level3Files }
     *
     */
    public void setLevel3Files(final Level3Files value) {
        this.level3Files = value;
    }

}
