//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="creationTime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="notValidAfter" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="logicalName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "metaData")
public class MetaData {

    @XmlAttribute(name = "creationTime", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String creationTime;
    @XmlAttribute(name = "notValidAfter", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String notValidAfter;
    @XmlAttribute(name = "logicalName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String logicalName;

    /**
     * Gets the value of the creationTime property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCreationTime(final String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the notValidAfter property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNotValidAfter() {
        return notValidAfter;
    }

    /**
     * Sets the value of the notValidAfter property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNotValidAfter(final String value) {
        this.notValidAfter = value;
    }

    /**
     * Gets the value of the logicalName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLogicalName() {
        return logicalName;
    }

    /**
     * Sets the value of the logicalName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLogicalName(final String value) {
        this.logicalName = value;
    }

}
