//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.ericsson.nms.security.nscs.iscf.xml
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TelnetAndFtpServers_QNAME = new QName("", "telnetAndFtpServers");
    private final static QName _LogonServerAddress_QNAME = new QName("", "logonServerAddress");
    private final static QName _LocalAuthenticationDB_QNAME = new QName("", "localAuthenticationDB");
    private final static QName _FileTransferClient_QNAME = new QName("", "fileTransferClient");
    private final static QName _LocalAuthorizationDB_QNAME = new QName("", "localAuthorizationDB");
    private final static QName _DataChallengePassword_QNAME = new QName("", "dataChallengePassword");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * com.ericsson.nms.security.nscs.iscf.xml
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnrollmentData }
     *
     */
    public EnrollmentData createEnrollmentData() {
        return new EnrollmentData();
    }

    /**
     * Create an instance of {@link ISCFEncryptedContent }
     *
     */
    public ISCFEncryptedContent createISCFEncryptedContent() {
        return new ISCFEncryptedContent();
    }

    /**
     * Create an instance of {@link Body }
     *
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link MetaData }
     *
     */
    public MetaData createMetaData() {
        return new MetaData();
    }

    /**
     * Create an instance of {@link Security }
     *
     */
    public Security createSecurity() {
        return new Security();
    }

    /**
     * Create an instance of {@link Level2 }
     *
     */
    public Level2 createLevel2() {
        return new Level2();
    }

    /**
     * Create an instance of {@link Level2ConfigSettings }
     *
     */
    public Level2ConfigSettings createLevel2ConfigSettings() {
        return new Level2ConfigSettings();
    }

    /**
     * Create an instance of {@link Level2Files }
     *
     */
    public Level2Files createLevel2Files() {
        return new Level2Files();
    }

    /**
     * Create an instance of {@link CertFile }
     *
     */
    public CertFile createCertFile() {
        return new CertFile();
    }

    /**
     * Create an instance of {@link EncryptedContent }
     *
     */
    public EncryptedContent createEncryptedContent() {
        return new EncryptedContent();
    }

    /**
     * Create an instance of {@link SecEnrollmentData }
     *
     */
    public SecEnrollmentData createSecEnrollmentData() {
        return new SecEnrollmentData();
    }

    /**
     * Create an instance of {@link ISCFEnrollmentData }
     *
     */
    public ISCFEnrollmentData createISCFEnrollmentData() {
        return new ISCFEnrollmentData();
    }

    /**
     * Create an instance of {@link Level3 }
     *
     */
    public Level3 createLevel3() {
        return new Level3();
    }

    /**
     * Create an instance of {@link Level3ConfigSettings }
     *
     */
    public Level3ConfigSettings createLevel3ConfigSettings() {
        return new Level3ConfigSettings();
    }

    /**
     * Create an instance of {@link AaServerIPAddressList }
     *
     */
    public AaServerIPAddressList createAaServerIPAddressList() {
        return new AaServerIPAddressList();
    }

    /**
     * Create an instance of {@link IpAddress }
     *
     */
    public IpAddress createIpAddress() {
        return new IpAddress();
    }

    /**
     * Create an instance of {@link Level3Files }
     *
     */
    public Level3Files createLevel3Files() {
        return new Level3Files();
    }

    /**
     * Create an instance of {@link Ipsec }
     *
     */
    public Ipsec createIpsec() {
        return new Ipsec();
    }

    /**
     * Create an instance of {@link IpsecFiles }
     *
     */
    public IpsecFiles createIpsecFiles() {
        return new IpsecFiles();
    }

    /**
     * Create an instance of {@link IpsecEnrollmentData }
     *
     */
    public IpsecEnrollmentData createIpsecEnrollmentData() {
        return new IpsecEnrollmentData();
    }

    /**
     * Create an instance of {@link Validators }
     *
     */
    public Validators createValidators() {
        return new Validators();
    }

    /**
     * Create an instance of {@link SecConfData }
     *
     */
    public SecConfData createSecConfData() {
        return new SecConfData();
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "telnetAndFtpServers")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTelnetAndFtpServers(String value) {
        return new JAXBElement<String>(_TelnetAndFtpServers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "logonServerAddress")
    public JAXBElement<String> createLogonServerAddress(String value) {
        return new JAXBElement<String>(_LogonServerAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link ISCFEncryptedContent }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "localAuthenticationDB")
    public JAXBElement<ISCFEncryptedContent> createLocalAuthenticationDB(ISCFEncryptedContent value) {
        return new JAXBElement<ISCFEncryptedContent>(_LocalAuthenticationDB_QNAME, ISCFEncryptedContent.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "fileTransferClient")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFileTransferClient(String value) {
        return new JAXBElement<String>(_FileTransferClient_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link ISCFEncryptedContent }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "localAuthorizationDB")
    public JAXBElement<ISCFEncryptedContent> createLocalAuthorizationDB(ISCFEncryptedContent value) {
        return new JAXBElement<ISCFEncryptedContent>(_LocalAuthorizationDB_QNAME, ISCFEncryptedContent.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link ISCFEncryptedContent }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "dataChallengePassword")
    public JAXBElement<ISCFEncryptedContent> createDataChallengePassword(ISCFEncryptedContent value) {
        return new JAXBElement<ISCFEncryptedContent>(_DataChallengePassword_QNAME, ISCFEncryptedContent.class, null, value);
    }

}
