//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}body"/>
 *         &lt;element ref="{}validators"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fileFormatVersion" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="1.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "body",
    "validators"
})
@XmlRootElement(name = "secConfData")
public class SecConfData {

    @XmlElement(required = true)
    protected Body body;
    @XmlElement(required = true)
    protected Validators validators;
    @XmlAttribute(name = "fileFormatVersion", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fileFormatVersion;

    /**
     * Gets the value of the body property.
     *
     * @return possible object is {@link Body }
     *
     */
    public Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     *
     * @param value allowed object is {@link Body }
     *
     */
    public void setBody(final Body value) {
        this.body = value;
    }

    /**
     * Gets the value of the validators property.
     *
     * @return possible object is {@link Validators }
     *
     */
    public Validators getValidators() {
        return validators;
    }

    /**
     * Sets the value of the validators property.
     *
     * @param value allowed object is {@link Validators }
     *
     */
    public void setValidators(final Validators value) {
        this.validators = value;
    }

    /**
     * Gets the value of the fileFormatVersion property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFileFormatVersion() {
        return fileFormatVersion;
    }

    /**
     * Sets the value of the fileFormatVersion property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFileFormatVersion(final String value) {
        this.fileFormatVersion = value;
    }

}
