//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 03:38:44 PM GMT 
//
package com.ericsson.nms.security.nscs.iscf.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}fileTransferClient" minOccurs="0"/>
 *         &lt;element ref="{}telnetAndFtpServers" minOccurs="0"/>
 *         &lt;element ref="{}level2" minOccurs="0"/>
 *         &lt;element ref="{}level3" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="wantedSecurityLevel" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="minimumSecurityLevel">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="userLabel">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="128"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileTransferClient",
    "telnetAndFtpServers",
    "level2",
    "level3"
})
@XmlRootElement(name = "security")
public class Security {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fileTransferClient;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String telnetAndFtpServers;
    protected Level2 level2;
    protected Level3 level3;
    @XmlAttribute(name = "wantedSecurityLevel", required = true)
    protected int wantedSecurityLevel;
    @XmlAttribute(name = "minimumSecurityLevel")
    protected Integer minimumSecurityLevel;
    @XmlAttribute(name = "userLabel")
    protected String userLabel;

    /**
     * Gets the value of the fileTransferClient property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFileTransferClient() {
        return fileTransferClient;
    }

    /**
     * Sets the value of the fileTransferClient property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFileTransferClient(final String value) {
        this.fileTransferClient = value;
    }

    /**
     * Gets the value of the telnetAndFtpServers property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTelnetAndFtpServers() {
        return telnetAndFtpServers;
    }

    /**
     * Sets the value of the telnetAndFtpServers property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTelnetAndFtpServers(final String value) {
        this.telnetAndFtpServers = value;
    }

    /**
     * Gets the value of the level2 property.
     *
     * @return possible object is {@link Level2 }
     *
     */
    public Level2 getLevel2() {
        return level2;
    }

    /**
     * Sets the value of the level2 property.
     *
     * @param value allowed object is {@link Level2 }
     *
     */
    public void setLevel2(final Level2 value) {
        this.level2 = value;
    }

    /**
     * Gets the value of the level3 property.
     *
     * @return possible object is {@link Level3 }
     *
     */
    public Level3 getLevel3() {
        return level3;
    }

    /**
     * Sets the value of the level3 property.
     *
     * @param value allowed object is {@link Level3 }
     *
     */
    public void setLevel3(final Level3 value) {
        this.level3 = value;
    }

    /**
     * Gets the value of the wantedSecurityLevel property.
     *
     * @return 
     */
    public int getWantedSecurityLevel() {
        return wantedSecurityLevel;
    }

    /**
     * Sets the value of the wantedSecurityLevel property.
     *
     * @param value
     */
    public void setWantedSecurityLevel(final int value) {
        this.wantedSecurityLevel = value;
    }

    /**
     * Gets the value of the minimumSecurityLevel property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getMinimumSecurityLevel() {
        return minimumSecurityLevel;
    }

    /**
     * Sets the value of the minimumSecurityLevel property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setMinimumSecurityLevel(final Integer value) {
        this.minimumSecurityLevel = value;
    }

    /**
     * Gets the value of the userLabel property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUserLabel() {
        return userLabel;
    }

    /**
     * Sets the value of the userLabel property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUserLabel(final String value) {
        this.userLabel = value;
    }

}
