//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 04:44:08 PM IST 
//


package com.ericsson.nms.security.nscs.cpp.ipsec.input.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DhcpClientIdentifierTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="DhcpClientIdentifierTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AUTOMATIC"/&gt;
 *     &lt;enumeration value="AUTOMATIC_MAC"/&gt;
 *     &lt;enumeration value="AUTOMATIC_SERIAL_NUMBER"/&gt;
 *     &lt;enumeration value="MANUAL"/&gt;
 *     &lt;enumeration value="NO_CLIENT_IDENTIFIER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DhcpClientIdentifierTypeEnum")
@XmlEnum
public enum DhcpClientIdentifierTypeEnum {

    AUTOMATIC,
    AUTOMATIC_MAC,
    AUTOMATIC_SERIAL_NUMBER,
    MANUAL,
    NO_CLIENT_IDENTIFIER;

    public String value() {
        return name();
    }

    public static DhcpClientIdentifierTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
