//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 11:27:55 AM IST 
//


package com.ericsson.nms.security.nscs.cpp.ipsec.input.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for diffieHellmanGroupType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="diffieHellmanGroupType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GROUP_2"/&gt;
 *     &lt;enumeration value="GROUP_14"/&gt;
 *     &lt;enumeration value="GROUP_19"/&gt;
 *     &lt;enumeration value="GROUP_20"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "diffieHellmanGroupType")
@XmlEnum
public enum DiffieHellmanGroupType {

    GROUP_2,
    GROUP_14,
    GROUP_19,
    GROUP_20;

    public String value() {
        return name();
    }

    public static DiffieHellmanGroupType fromValue(String v) {
        return valueOf(v);
    }

}
