//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 11:27:55 AM IST 
//


package com.ericsson.nms.security.nscs.cpp.ipsec.input.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ikePeerIntegrityAlgorithm.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="ikePeerIntegrityAlgorithm"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AES_XCBC_MAC_96"/&gt;
 *     &lt;enumeration value="HMAC_MD5_96"/&gt;
 *     &lt;enumeration value="HMAC_SHA_1_96"/&gt;
 *     &lt;enumeration value="HMAC_SHA2_256_128"/&gt;
 *     &lt;enumeration value="AES_GCM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ikePeerIntegrityAlgorithm")
@XmlEnum
public enum IkePeerIntegrityAlgorithm {

    AES_XCBC_MAC_96("AES_XCBC_MAC_96"),
    @XmlEnumValue("HMAC_MD5_96")
    HMAC_MD_5_96("HMAC_MD5_96"),
    HMAC_SHA_1_96("HMAC_SHA_1_96"),
    @XmlEnumValue("HMAC_SHA2_256_128")
    HMAC_SHA_2_256_128("HMAC_SHA2_256_128"),
    AES_GCM("AES_GCM");
    private final String value;

    IkePeerIntegrityAlgorithm(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IkePeerIntegrityAlgorithm fromValue(String v) {
        for (IkePeerIntegrityAlgorithm c: IkePeerIntegrityAlgorithm.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
