//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 11:27:55 AM IST 
//


package com.ericsson.nms.security.nscs.cpp.ipsec.input.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ikePeerEncryptionAlgorithm.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="ikePeerEncryptionAlgorithm"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AES_CBC_128"/&gt;
 *     &lt;enumeration value="AES_CBC_256"/&gt;
 *     &lt;enumeration value="ALG_3DES_CBC"/&gt;
 *     &lt;enumeration value="AES_128_GCM_128"/&gt;
 *     &lt;enumeration value="AES_256_GCM_128"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ikePeerEncryptionAlgorithm")
@XmlEnum
public enum IkePeerEncryptionAlgorithm {

    AES_CBC_128("AES_CBC_128"),
    AES_CBC_256("AES_CBC_256"),
    @XmlEnumValue("ALG_3DES_CBC")
    ALG_3_DES_CBC("ALG_3DES_CBC"),
    AES_128_GCM_128("AES_128_GCM_128"),
    AES_256_GCM_128("AES_256_GCM_128");
    private final String value;

    IkePeerEncryptionAlgorithm(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IkePeerEncryptionAlgorithm fromValue(String v) {
        for (IkePeerEncryptionAlgorithm c: IkePeerEncryptionAlgorithm.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
