//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 04:44:08 PM IST 
//


package com.ericsson.nms.security.nscs.cpp.ipsec.input.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IpVersionTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="IpVersionTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="IP_V4"/&gt;
 *     &lt;enumeration value="IP_V6"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IpVersionTypeEnum")
@XmlEnum
public enum IpVersionTypeEnum {

    @XmlEnumValue("IP_V4")
    IP_V_4("IP_V4"),
    @XmlEnumValue("IP_V6")
    IP_V_6("IP_V6");
    private final String value;

    IpVersionTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IpVersionTypeEnum fromValue(String v) {
        for (IpVersionTypeEnum c: IpVersionTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
