//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.28 at 04:08:09 PM IST 
//


package com.ericsson.nms.security.nscs.cpp.ipsec.input.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.nms.security.nscs.cpp.ipsec.input.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.nms.security.nscs.cpp.ipsec.input.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nodes }
     * @return nodes
     */
    public Nodes createNodes() {
        return new Nodes();
    }

    /**
     * Create an instance of {@link Nodes.Node }
     * @return nodes
     *
     */
    public Nodes.Node createNodesNode() {
        return new Nodes.Node();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic createNodesNodeSiteBasic() {
        return new Nodes.Node.SiteBasic();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.Synchronization }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.Synchronization createNodesNodeSiteBasicSynchronization() {
        return new Nodes.Node.SiteBasic.Synchronization();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.Synchronization.NodeGroupSyncMember }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.Synchronization.NodeGroupSyncMember createNodesNodeSiteBasicSynchronizationNodeGroupSyncMember() {
        return new Nodes.Node.SiteBasic.Synchronization.NodeGroupSyncMember();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem createNodesNodeSiteBasicIpSystem() {
        return new Nodes.Node.SiteBasic.IpSystem();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.AccessControlList }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.AccessControlList createNodesNodeSiteBasicIpSystemAccessControlList() {
        return new Nodes.Node.SiteBasic.IpSystem.AccessControlList();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.IpSec }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.IpSec createNodesNodeSiteBasicIpSystemIpSec() {
        return new Nodes.Node.SiteBasic.IpSystem.IpSec();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.IpSec.IpSecTunnel }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.IpSec.IpSecTunnel createNodesNodeSiteBasicIpSystemIpSecIpSecTunnel() {
        return new Nodes.Node.SiteBasic.IpSystem.IpSec.IpSecTunnel();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.IpSec.IkePeer }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.IpSec.IkePeer createNodesNodeSiteBasicIpSystemIpSecIkePeer() {
        return new Nodes.Node.SiteBasic.IpSystem.IpSec.IkePeer();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.IpAccessHostEt }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.IpAccessHostEt createNodesNodeSiteBasicIpSystemIpAccessHostEt() {
        return new Nodes.Node.SiteBasic.IpSystem.IpAccessHostEt();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.ENodeBFunction }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.ENodeBFunction createNodesNodeSiteBasicENodeBFunction() {
        return new Nodes.Node.SiteBasic.ENodeBFunction();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.ENodeBFunction.RbsConfiguration }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.ENodeBFunction.RbsConfiguration createNodesNodeSiteBasicENodeBFunctionRbsConfiguration() {
        return new Nodes.Node.SiteBasic.ENodeBFunction.RbsConfiguration();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.Ip }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.Ip createNodesNodeSiteBasicIp() {
        return new Nodes.Node.SiteBasic.Ip();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.Ip.IpRoutingTable }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.Ip.IpRoutingTable createNodesNodeSiteBasicIpIpRoutingTable() {
        return new Nodes.Node.SiteBasic.Ip.IpRoutingTable();
    }

    /**
     * Create an instance of {@link Nodes.Node.DisableOMConfiguration }
     * @return nodes
     *
     */
    public Nodes.Node.DisableOMConfiguration createNodesNodeDisableOMConfiguration() {
        return new Nodes.Node.DisableOMConfiguration();
    }

    /**
     * Create an instance of {@link Nodes.Node.EnableOMConfiguration2 }
     * @return nodes
     *
     */
    public Nodes.Node.EnableOMConfiguration2 createNodesNodeEnableOMConfiguration2() {
        return new Nodes.Node.EnableOMConfiguration2();
    }

    /**
     * Create an instance of {@link Nodes.Node.EnableOMConfiguration1 }
     * @return nodes
     *
     */
    public Nodes.Node.EnableOMConfiguration1 createNodesNodeEnableOMConfiguration1() {
        return new Nodes.Node.EnableOMConfiguration1();
    }

    /**
     * Create an instance of {@link Nodes.Node.EnableOMConfiguration1 .IkePeerAllowedTransforms }
     * @return nodes
     *
     */
    public Nodes.Node.EnableOMConfiguration1 .IkePeerAllowedTransforms createNodesNodeEnableOMConfiguration1IkePeerAllowedTransforms() {
        return new Nodes.Node.EnableOMConfiguration1 .IkePeerAllowedTransforms();
    }

    /**
     * Create an instance of {@link Nodes.Node.EnableOMConfiguration1 .IpSecTunnelAllowedTransforms }
     * @return nodes
     *
     */
    public Nodes.Node.EnableOMConfiguration1 .IpSecTunnelAllowedTransforms createNodesNodeEnableOMConfiguration1IpSecTunnelAllowedTransforms() {
        return new Nodes.Node.EnableOMConfiguration1 .IpSecTunnelAllowedTransforms();
    }

    /**
     * Create an instance of {@link Nodes.Node.InstallTrustCertificates }
     * @return nodes
     *
     */
    public Nodes.Node.InstallTrustCertificates createNodesNodeInstallTrustCertificates() {
        return new Nodes.Node.InstallTrustCertificates();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.Format }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.Format createNodesNodeSiteBasicFormat() {
        return new Nodes.Node.SiteBasic.Format();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.ManagedElementData }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.ManagedElementData createNodesNodeSiteBasicManagedElementData() {
        return new Nodes.Node.SiteBasic.ManagedElementData();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpInterface }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpInterface createNodesNodeSiteBasicIpInterface() {
        return new Nodes.Node.SiteBasic.IpInterface();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.TuSyncRef }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.TuSyncRef createNodesNodeSiteBasicTuSyncRef() {
        return new Nodes.Node.SiteBasic.TuSyncRef();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.GpsSyncRef }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.GpsSyncRef createNodesNodeSiteBasicGpsSyncRef() {
        return new Nodes.Node.SiteBasic.GpsSyncRef();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.GpsOutSyncLink }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.GpsOutSyncLink createNodesNodeSiteBasicGpsOutSyncLink() {
        return new Nodes.Node.SiteBasic.GpsOutSyncLink();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.HptsiSyncRef }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.HptsiSyncRef createNodesNodeSiteBasicHptsiSyncRef() {
        return new Nodes.Node.SiteBasic.HptsiSyncRef();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.PacketFrequencySyncRef }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.PacketFrequencySyncRef createNodesNodeSiteBasicPacketFrequencySyncRef() {
        return new Nodes.Node.SiteBasic.PacketFrequencySyncRef();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.PacketTimeSyncRef }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.PacketTimeSyncRef createNodesNodeSiteBasicPacketTimeSyncRef() {
        return new Nodes.Node.SiteBasic.PacketTimeSyncRef();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.TimingUnit }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.TimingUnit createNodesNodeSiteBasicTimingUnit() {
        return new Nodes.Node.SiteBasic.TimingUnit();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.Synchronization.NodeGroupSyncMember.SyncRiPortCandidate }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.Synchronization.NodeGroupSyncMember.SyncRiPortCandidate createNodesNodeSiteBasicSynchronizationNodeGroupSyncMemberSyncRiPortCandidate() {
        return new Nodes.Node.SiteBasic.Synchronization.NodeGroupSyncMember.SyncRiPortCandidate();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.VpnInterface }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.VpnInterface createNodesNodeSiteBasicIpSystemVpnInterface() {
        return new Nodes.Node.SiteBasic.IpSystem.VpnInterface();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.DnsResolver }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.DnsResolver createNodesNodeSiteBasicIpSystemDnsResolver() {
        return new Nodes.Node.SiteBasic.IpSystem.DnsResolver();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.Ipv6Interface }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.Ipv6Interface createNodesNodeSiteBasicIpSystemIpv6Interface() {
        return new Nodes.Node.SiteBasic.IpSystem.Ipv6Interface();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.Ipv6 }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.Ipv6 createNodesNodeSiteBasicIpSystemIpv6() {
        return new Nodes.Node.SiteBasic.IpSystem.Ipv6();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.AccessControlList.AclEntries }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.AccessControlList.AclEntries createNodesNodeSiteBasicIpSystemAccessControlListAclEntries() {
        return new Nodes.Node.SiteBasic.IpSystem.AccessControlList.AclEntries();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.IpSec.IpSecTunnel.AllowedTransforms }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.IpSec.IpSecTunnel.AllowedTransforms createNodesNodeSiteBasicIpSystemIpSecIpSecTunnelAllowedTransforms() {
        return new Nodes.Node.SiteBasic.IpSystem.IpSec.IpSecTunnel.AllowedTransforms();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.IpSec.IpSecTunnel.TsRemoteIpAddressRanges }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.IpSec.IpSecTunnel.TsRemoteIpAddressRanges createNodesNodeSiteBasicIpSystemIpSecIpSecTunnelTsRemoteIpAddressRanges() {
        return new Nodes.Node.SiteBasic.IpSystem.IpSec.IpSecTunnel.TsRemoteIpAddressRanges();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.IpSec.IkePeer.AllowedTransforms }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.IpSec.IkePeer.AllowedTransforms createNodesNodeSiteBasicIpSystemIpSecIkePeerAllowedTransforms() {
        return new Nodes.Node.SiteBasic.IpSystem.IpSec.IkePeer.AllowedTransforms();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.IpSystem.IpAccessHostEt.IpSyncRef }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.IpSystem.IpAccessHostEt.IpSyncRef createNodesNodeSiteBasicIpSystemIpAccessHostEtIpSyncRef() {
        return new Nodes.Node.SiteBasic.IpSystem.IpAccessHostEt.IpSyncRef();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.ENodeBFunction.RbsConfiguration.WantedPosition }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.ENodeBFunction.RbsConfiguration.WantedPosition createNodesNodeSiteBasicENodeBFunctionRbsConfigurationWantedPosition() {
        return new Nodes.Node.SiteBasic.ENodeBFunction.RbsConfiguration.WantedPosition();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.Ip.IpHostLink }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.Ip.IpHostLink createNodesNodeSiteBasicIpIpHostLink() {
        return new Nodes.Node.SiteBasic.Ip.IpHostLink();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.Ip.OaMAlternativeAccessSource }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.Ip.OaMAlternativeAccessSource createNodesNodeSiteBasicIpOaMAlternativeAccessSource() {
        return new Nodes.Node.SiteBasic.Ip.OaMAlternativeAccessSource();
    }

    /**
     * Create an instance of {@link Nodes.Node.SiteBasic.Ip.IpRoutingTable.StaticRoutes }
     * @return nodes
     *
     */
    public Nodes.Node.SiteBasic.Ip.IpRoutingTable.StaticRoutes createNodesNodeSiteBasicIpIpRoutingTableStaticRoutes() {
        return new Nodes.Node.SiteBasic.Ip.IpRoutingTable.StaticRoutes();
    }

    /**
     * Create an instance of {@link Nodes.Node.DisableOMConfiguration.RemoveTrust }
     * @return nodes
     *
     */
    public Nodes.Node.DisableOMConfiguration.RemoveTrust createNodesNodeDisableOMConfigurationRemoveTrust() {
        return new Nodes.Node.DisableOMConfiguration.RemoveTrust();
    }

    /**
     * Create an instance of {@link Nodes.Node.EnableOMConfiguration2 .TsRemoteIpAddressRanges }
     * @return nodes
     *
     */
    public Nodes.Node.EnableOMConfiguration2 .TsRemoteIpAddressRanges createNodesNodeEnableOMConfiguration2TsRemoteIpAddressRanges() {
        return new Nodes.Node.EnableOMConfiguration2 .TsRemoteIpAddressRanges();
    }

    /**
     * Create an instance of {@link Nodes.Node.EnableOMConfiguration1 .TsRemoteIpAddressRanges }
     * @return nodes
     *
     */
    public Nodes.Node.EnableOMConfiguration1 .TsRemoteIpAddressRanges createNodesNodeEnableOMConfiguration1TsRemoteIpAddressRanges() {
        return new Nodes.Node.EnableOMConfiguration1 .TsRemoteIpAddressRanges();
    }

    /**
     * Create an instance of {@link Nodes.Node.EnableOMConfiguration1 .IkePeerAllowedTransforms.IkePeerAllowedTransform }
     * @return nodes
     *
     */
    public Nodes.Node.EnableOMConfiguration1 .IkePeerAllowedTransforms.IkePeerAllowedTransform createNodesNodeEnableOMConfiguration1IkePeerAllowedTransformsIkePeerAllowedTransform() {
        return new Nodes.Node.EnableOMConfiguration1 .IkePeerAllowedTransforms.IkePeerAllowedTransform();
    }

    /**
     * Create an instance of {@link Nodes.Node.EnableOMConfiguration1 .IpSecTunnelAllowedTransforms.IpSecTunnelAllowedTransform }
     * @return nodes
     *
     */
    public Nodes.Node.EnableOMConfiguration1 .IpSecTunnelAllowedTransforms.IpSecTunnelAllowedTransform createNodesNodeEnableOMConfiguration1IpSecTunnelAllowedTransformsIpSecTunnelAllowedTransform() {
        return new Nodes.Node.EnableOMConfiguration1 .IpSecTunnelAllowedTransforms.IpSecTunnelAllowedTransform();
    }

}
