//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 04:44:08 PM IST 
//


package com.ericsson.nms.security.nscs.cpp.ipsec.input.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OwnIdTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="OwnIdTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AUTOMATIC"/&gt;
 *     &lt;enumeration value="IP_V4_ADDRESS"/&gt;
 *     &lt;enumeration value="FQDN"/&gt;
 *     &lt;enumeration value="AUTOMATIC_DN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OwnIdTypeEnum")
@XmlEnum
public enum OwnIdTypeEnum {

    AUTOMATIC("AUTOMATIC"),
    @XmlEnumValue("IP_V4_ADDRESS")
    IP_V_4_ADDRESS("IP_V4_ADDRESS"),
    FQDN("FQDN"),
    AUTOMATIC_DN("AUTOMATIC_DN");
    private final String value;

    OwnIdTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OwnIdTypeEnum fromValue(String v) {
        for (OwnIdTypeEnum c: OwnIdTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
