//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 04:44:08 PM IST 
//


package com.ericsson.nms.security.nscs.cpp.ipsec.input.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pseudoRandomFunctionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="pseudoRandomFunctionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *     &lt;enumeration value="AES_XCBC_PRF128"/&gt;
 *     &lt;enumeration value="HMAC_SHA1"/&gt;
 *     &lt;enumeration value="HMAC_MD5"/&gt;
 *     &lt;enumeration value="HMAC_SHA2_256"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "pseudoRandomFunctionType")
@XmlEnum
public enum PseudoRandomFunctionType {

    @XmlEnumValue("AES_XCBC_PRF128")
    AES_XCBC_PRF_128("AES_XCBC_PRF128"),
    @XmlEnumValue("HMAC_SHA1")
    HMAC_SHA_1("HMAC_SHA1"),
    @XmlEnumValue("HMAC_MD5")
    HMAC_MD_5("HMAC_MD5"),
    @XmlEnumValue("HMAC_SHA2_256")
    HMAC_SHA_2_256("HMAC_SHA2_256");
    private final String value;

    PseudoRandomFunctionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PseudoRandomFunctionType fromValue(String v) {
        for (PseudoRandomFunctionType c: PseudoRandomFunctionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
