//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 04:44:08 PM IST 
//


package com.ericsson.nms.security.nscs.cpp.ipsec.input.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QualityLevelEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="QualityLevelEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="QL_PRC"/&gt;
 *     &lt;enumeration value="QL_SSU_A"/&gt;
 *     &lt;enumeration value="QL_SSU_B"/&gt;
 *     &lt;enumeration value="QL_SEC_QL_EEC"/&gt;
 *     &lt;enumeration value="QL_PRS"/&gt;
 *     &lt;enumeration value="QL_STU"/&gt;
 *     &lt;enumeration value="QL_ST2"/&gt;
 *     &lt;enumeration value="QL_TNC"/&gt;
 *     &lt;enumeration value="QL_ST3E"/&gt;
 *     &lt;enumeration value="QL_ST3_QL_EEC"/&gt;
 *     &lt;enumeration value="QL_SMC"/&gt;
 *     &lt;enumeration value="QL_UNK"/&gt;
 *     &lt;enumeration value="QL_SEC"/&gt;
 *     &lt;enumeration value="NOT_DEFINED"/&gt;
 *     &lt;enumeration value="QL_GPS"/&gt;
 *     &lt;enumeration value="QL_PRTC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "QualityLevelEnum")
@XmlEnum
public enum QualityLevelEnum {

    QL_PRC("QL_PRC"),
    QL_SSU_A("QL_SSU_A"),
    QL_SSU_B("QL_SSU_B"),
    QL_SEC_QL_EEC("QL_SEC_QL_EEC"),
    QL_PRS("QL_PRS"),
    QL_STU("QL_STU"),
    @XmlEnumValue("QL_ST2")
    QL_ST_2("QL_ST2"),
    QL_TNC("QL_TNC"),
    @XmlEnumValue("QL_ST3E")
    QL_ST_3_E("QL_ST3E"),
    @XmlEnumValue("QL_ST3_QL_EEC")
    QL_ST_3_QL_EEC("QL_ST3_QL_EEC"),
    QL_SMC("QL_SMC"),
    QL_UNK("QL_UNK"),
    QL_SEC("QL_SEC"),
    NOT_DEFINED("NOT_DEFINED"),
    QL_GPS("QL_GPS"),
    QL_PRTC("QL_PRTC");
    private final String value;

    QualityLevelEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QualityLevelEnum fromValue(String v) {
        for (QualityLevelEnum c: QualityLevelEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
