/*
 * COPYRIGHT Ericsson 2014
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 */

package com.ericsson.nms.security.nscs.api.iscf;

import java.io.Serializable;

/**
 * Class encapsulating data required for node integration that has
 * been generated by IscfService
 *
 * @author ealemca
 */
public class IscfResponse implements Serializable {

    /**
     * XML content including &lt;validators&gt;
     */
    private byte[] iscfContent;

    /**
     * The RIC used to encrypt content during ISCF generation
     */
    private String rbsIntegrityCode;

    /**
     * The Security Configuration Checksum (SCC) calculated from
     * data gathered by IscfService
     */
    private String securityConfigChecksum;

    /**
     * Get the ISCF XML content
     *
     * @return iscfContent
     */
    public byte[] getIscfContent() {
        return iscfContent;
    }

    /**
     * Set the ISCF XML content
     *
     * @param iscfContent the iscfContent
     */
    public void setIscfContent(final byte[] iscfContent) {
        this.iscfContent = iscfContent;
    }

    /**
     * Get the RBS Integrity Code (RIC)
     *
     * @return rbsIntegrityCode
     */
    public String getRbsIntegrityCode() {
        return rbsIntegrityCode;
    }

    /**
     * Set the RBS Integrity Code (RIC)
     *
     * @param rbsIntegrityCode the rbsIntegrityCode
     */
    public void setRbsIntegrityCode(final String rbsIntegrityCode) {
        this.rbsIntegrityCode = rbsIntegrityCode;
    }

    /**
     * Get the Security Configuration Checksum (SCC)
     *
     * @return securityConfigChecksum
     */
    public String getSecurityConfigChecksum() {
        return securityConfigChecksum;
    }

    /**
     * Set the Security Configuration Checksum (SCC)
     *
     * @param securityConfigChecksum the securityConfigChecksum
     */
    public void setSecurityConfigChecksum(final String securityConfigChecksum) {
        this.securityConfigChecksum = securityConfigChecksum;
    }

}
