/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2017
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/

package com.ericsson.nms.security.nscs.utilities;

/**
 * This class holds the common constant values.
 *
 * @author zlaxsri
 */
public class Constants {
    public static final String WARNING = "Warning";
    public static final String ERROR = "Error";
    public static final String FATAL = "Fatal";

    public static final String ATTRIBUTE_USERID = "userId";
    public static final String ATTRIBUTE_CATEGORY = "category";
    public static final String PRIVATE_CATEGORY = "Private";
    public static final String PUBLIC_CATEGORY = "Public";
    public static final String AUTOGENERATED_COLLECTIONS_USER_ID = "networkExplorer";
    public static final String ATTRIBUTE_MO_LIST_COLLECTION = "moList";
    public static final String SAVED_SEARCH_OR_COLLECTION_NAMES_SYNTAX = "[a-zA-Z0-9_.\\-^\\s]+";

    public static final String EMPTY_STRING = "";

    // Command file properties
    public static final String FILE_NAME = "fileName";
    public static final String FILE_PATH = "filePath";
    public static final String FILE_EXT_TXT = "txt";
    public static final String FILE_EXT_XML = "xml";

    public static final String ECDSA_256 = "ECDSA_256";
    public static final String ECDSA_384 = "ECDSA_384";
    public static final String ECDSA_521 = "ECDSA_521";
    public static final String ECDSA_SECP_256_R1 = "ECDSA_SECP_256_R1";
    public static final String ECDSA_SECP_384_R1 = "ECDSA_SECP_384_R1";
    public static final String ECDSA_SECP_521_R1 = "ECDSA_SECP_521_R1";
    public static final String REMOVE_UNWANTED_SQUARE_BRACKETS_REGEX = "\\[|\\]";
    public static final String COMMA_DELIMITER = ",";

    public static final String DOMAINCOMPONENT = "domainComponent";
    public static final String DC = "DC";


}
