"secadm" (* slogan = "Manages security configuration and administration on network nodes" *) WS "crl" (* slogan = "Downloads CRL on demand, on a single or multiple nodes" *) WS "download" (* slogan = "CRL download. Tip: dl for short" *) WS DL_TARGET_NODES

DL_TARGET_NODES ::= ( DL_NODE_LIST | DL_NODE_FILE | DL_SAVED_SEARCH | DL_COLLECTION )

DL_NODE_LIST ::= ( "-n" (* hide = "true" *) | "--nodelist" (* slogan = "Specify the list of nodes. Tip: -n for short" *) ) WS DL_NODE_NAME { ( "," | ";" ) (* slogan = "Comma used to add another node name to the list." *) DL_NODE_NAME }

DL_NODE_NAME ::= [ "MeContext=" ] <node_name> (* slogan = "Scope the Command using Node names. E.g. MyNode1,MyNode2" *) )

DL_NODE_FILE ::= ( "-nf" (* hide = "true" *) | "--nodefile" (* slogan = "Specify the file containing a list of nodes. Tip: -nf for short" *) ) WS "file:" <file_name> (* inputType = "fileName" slogan = "Specify a file containing a list of nodes" *)

DL_SAVED_SEARCH ::= ( "-sa" (* hide = "true" *) | "--savedsearch" (* slogan = "Specify the savedsearch name which contains a list of nodes. Tip: -sa for short" *) ) WS SAVED_SEARCH_NAME { "," (* slogan = "Comma used to add another savedsearch name to the list." *) SAVED_SEARCH_NAME }

DL_COLLECTION ::= ( "-co" (* hide = "true" *) | "--collection" (* slogan = "Specify the collection name which contains a list of nodes. Tip: -co for short" *) ) WS COLLECTION_NAME { "," (* slogan = "Comma used to add another collection name to the list." *) COLLECTION_NAME }

SAVED_SEARCH_NAME ::= <saved_search_name> (* slogan = "Scope the Command using saved search names. E.g. MySavedSearch1, MySavedSearch2" *) )

COLLECTION_NAME ::= <collection_name> (* slogan = "Scope the Command using saved search names. E.g. MyCollection1, MyCollection2" *) )