"secadm" (* slogan = "Get Password for a node specific user" *) WS "ftp" (* slogan = "Get Password for node specific user" *) WS PASSWORD_GET

PASSWORD_GET ::=  "get" (* slogan = "Get Password for Specific Node Type" *) [ NE_TYPE ]

NE_TYPE ::= WS ( "-nt" (* hide = "true" *) | "--netype" (* slogan = "Specify the node type E.g. SBG-IS" *) ) WS <netype> (* slogan = "Specify the name of the netype. Tip: -nt for short" *)
